[package]
name = "example-tls-reload"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-stream = "0.3.2"
poem = { path = "../../../poem", features = ["tls"]}
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros", "time"] }
tracing-subscriber = "0.2.24"
