[all]
workspace = true
avoid_cfg_tarpaulin = true
all-features = true
exclude = ["poem-dbsession"]
exclude-files = [
  "examples/**/*",
  "poem-derive/**/*",
  "poem-openapi-derive/**/*",
  "poem-dbsession/**/*",
  "poem-grpc-build/**/*",
]
