[package]
name = "poem"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"
description = "Poem is an easy-to-use web framework for Rust"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/poem/"
homepage = "https://github.com/poem/poem"
repository = "https://github.com/poem/poem"
keywords = ["http", "web", "framework", "async"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket",
]

[dependencies]
async-trait = "0.1.51"
anyhow = "1.0.42"
bytes = "1.0.1"
futures-util = "0.3.16"
http = "0.2.4"
hyper = { version = "0.14.11", features = ["http1", "http2", "server", "runtime", "stream"] }
mime = "0.3.16"
multer = { version = "2.0.1", features = ["tokio"] }
tokio = { version = "1.9.0", features = ["sync", "rt"] }
tokio-util = { version = "0.6.7", features = ["io"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"

[dev-dependencies]
tokio = { version = "1.9.0", features = ["rt-multi-thread", "macros"] }
