[package]
name = "example-upload"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["tracing", "multipart"] }
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
