[package]
name = "example-openapi-custom-payload"
version = "0.1.0"
edition = "2021"

[dependencies]
bcs = "0.1.3"
mime = { version = "0.3.16" }
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi", features = ["swagger-ui"] }
serde = { version = "1.0.139", features = ["derive"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "sync"] }

