[package]
name = "poem-openapi"
version = "1.0.34"
authors = ["sunli <scott_s829@163.com>"]
edition = "2021"
description = "OpenAPI support for Poem."
readme = "README.md"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/poem/"
homepage = "https://github.com/poem-web/poem"
repository = "https://github.com/poem-web/poem"
keywords = ["http", "async", "openapi", "swagger"]
categories = [
    "network-programming",
    "asynchronous",
]

[features]
default = ["swagger-ui"]

swagger-ui = []

[dependencies]
poem-openapi-derive = { path = "../poem-openapi-derive", version = "1.0.19" }
poem = { path = "../poem", version = "1.0.14", features = ["multipart", "tempfile", "cookie"] }

tokio = { version = "1.12.0", features = ["fs"] }
serde_json = "1.0.68"
base64 = "0.13.0"
serde = { version = "1.0.130", features = ["derive"] }
derive_more = "0.99.16"
num-traits = "0.2.14"
regex = "1.5.4"
typed-headers = "0.2.0"
mime = "0.3.16"

# Feature optional dependencies
chrono = { version = "0.4.19", optional = true }
thiserror = "1.0.30"

[dev-dependencies]
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
