[package]
name = "poem-todos"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "1.2.7"
poem-openapi = { version = "1.2.7", features = ["swagger-ui"] }
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.8"
