[package]
name = "example-opentelemetry"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["opentelemetry", "prometheus"] }
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2.24"
opentelemetry = { version = "0.16.0", features = ["metrics"] }
opentelemetry-http = { version = "0.5.0" }
reqwest = "0.11.6"

[[bin]]
name = "example-opentelemetry-client"
path = "src/client.rs"
