[package]
name = "poem-grpc"
version = "1.3.37"
edition = "2021"

[features]
default = []
json-codec = ["serde", "serde_json"]

[dependencies]
poem = { path = "../poem", version = "1.3.37" }

futures-util = { version = "0.3.17" }
hyper = { version = "0.14.20", features = ["client"] }
async-stream = "0.3.3"
tokio = { version = "1.20.1", features = ["io-util", "rt", "sync"] }
flate2 = "1.0.24"
itoa = "1.0.2"
percent-encoding = "2.1.0"
bytes = "1.2.0"
prost = "0.11.0"
base64 = "0.13.0"
prost-types = "0.11.0"
tokio-stream = { version = "0.1.9", features = ["sync"] }
serde = { version = "1.0.140", optional = true }
serde_json = { version = "1.0.82", optional = true }

[build-dependencies]
poem-grpc-build = { path = "../poem-grpc-build", version = "1.3.37" }
