[package]
name = "example-opentelemetry"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { workspace = true, features = ["opentelemetry"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true
opentelemetry = { version = "0.21.0", features = ["metrics"] }
opentelemetry_sdk = "0.21.0"
opentelemetry-http = { version = "0.10.0" }
opentelemetry-jaeger = { version = "0.20.0", features = [
    "rt-tokio",
    "collector_client",
    "hyper_collector_client",
] }
reqwest = "0.11.6"

[[bin]]
name = "example-opentelemetry-client"
path = "src/client.rs"

[[bin]]
name = "example-opentelemetry-server1"
path = "src/server1.rs"

[[bin]]
name = "example-opentelemetry-server2"
path = "src/server2.rs"
