name: Book

on:
  push:
    branches:
      - release
    paths:
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  deploy_en:
    name: Deploy book on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
      - name: Render book
        run: |
          mdbook build -d gh-pages docs/en
          mdbook build -d gh-pages docs/zh-CN
          mkdir docs/gh-pages
          mv docs/en/gh-pages docs/gh-pages/en
          mv docs/zh-CN/gh-pages docs/gh-pages/zh-CN
          mv docs/index.html docs/gh-pages
          cp -r docs/assets docs/gh-pages/en
          cp -r docs/assets docs/gh-pages/zh-CN
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          emptyCommits: true
          keepFiles: false
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: docs/gh-pages
          cname: poem.rs
